Crear lógica de estadísticas de propietario /272
Cohabify/Cohabify pull request #275
Opened 2024-04-05 17:24 UTC by nxniya

2024-04-06 21:05 UTC, Miguel-Angel-Roldan-Garcia requested changes

2024-04-06 21:05 UTC, Miguel-Angel-Roldan-Garcia commented on backend/src/main/java/org/ispp4/cohabify/houseAdvertisement/HouseAdvertisementController.java
> +        }
Este bloque de código necesitaría un check para mirar primero si el getCurrentUser es null (Si es null se suma igualmente). Ya que la página que hace fetch a este método se puede visualizar siendo anónimo (Sin estar logeado). Actualmente provoca una excepción entrar en los detalles de anuncio de vivienda sin estar logeado, lo cual es una acción legal.
Algo como: if(global.getCurrentUser() == null || !advertisement.get().getAuthor... .getUsername())){

2024-04-07 09:49 UTC, nxniya commented on backend/src/main/java/org/ispp4/cohabify/houseAdvertisement/HouseAdvertisementController.java
> +        }
🫡🎀

2024-04-07 10:22 UTC, Miguel-Angel-Roldan-Garcia approved these changes
Ya esta perfecto.

2024-04-07 10:23 UTC, merged