Añadir mapa en la página de detalles de piso /56
Cohabify/Cohabify pull request #313
Opened 2024-04-20 16:27 UTC by guigalde

2024-04-20 19:20 UTC, juamornav3 requested changes
En backend no se cambia el geojson point en crear y en editar y falta el mapa en la pantalla de editar.

2024-04-21 11:52 UTC, juamornav3 requested changes
Hace falta una validación tanto en el formulario de crear y editar anuncio de vivienda, con un mensaje para que el usuario coloque la marca de la ubicación en el mapa. Por lo demás todo bien

2024-04-21 16:45 UTC, olemornav approved these changes
La funcionalidad se ha implementado correctamente

2024-04-21 16:47 UTC, juamornav3 approved these changes
Todo correcto

2024-04-21 16:47 UTC, merged