Añadir paginación a listados /333
Cohabify/Cohabify pull request #345
Opened 2024-05-02 17:27 UTC by guigalde

2024-05-06 10:14 UTC, marcallop7 requested changes
Los datos iniciales no son demasiado realistas ya que son todas iguales deberías de cambiar eso, a lo mejor no poner tantas con que en la segunda página haya al menos una debería de bastar, cambiando las imágenes, el nombre, los precios, la ubicación, ect, todo lo más realista posible.

Además corrige la primera vivienda que dale porque tiene las coordenadas invertidas ya que dani ya cambió las coordenadas de las 4 primeras viviendas para que salieran bien. Si tienes dudas pregunta a dani.

Por último en el listado deberías de poner Página de 1 a 2 no en inglés.

2024-05-14 18:07 UTC, juanrg8 reviewed
Todo correcto

2024-05-14 20:35 UTC, guigalde reviewed
La solicitud de cambios ha sido completada

2024-05-14 22:59 UTC, juanrg8 approved these changes

2024-05-14 23:00 UTC, juanrg8 approved these changes

2024-05-15 09:14 UTC, marcallop7 commented
Veo que se ha arreglado todo, pero por si acaso yo cambiaria la ubicación de los pisos que no son de España para que solo sean de aquí debido que de momento no somos internacionales. Cuando lo cambies te aceptare la pr. Muchas gracias y mucho ánimo, ya no queda nada.

2024-05-15 09:16 UTC, marcallop7 commented
Y también acuérdate que la primera vivienda (la de Triana) en el mapa aparezca en Triana de verdad, muy importante.

2024-05-15 17:32 UTC, merged